import "./globals.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
let Navbar = dynamic(() =>import("@/components/Navbar") );
let Footer = dynamic(() =>import("@/components/Footer") );


import { SupabaseProvider } from "@/components/providers/supabase-provider";

import { SupabaseAuthProvider } from "@/components/providers/supabase-auth-provider";

import createClient from "../../utils/supabase-server";

export const revalidate=0;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let supabase = createClient();
;
  let {
    data: { session },
  } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <SupabaseAuthProvider serverSession={session}>
            <Navbar />
            {children}
          </SupabaseAuthProvider>
          <Footer />
        </SupabaseProvider>
      </body>
    </html>
  );
}
