import "./globals.css";

import { Catamaran } from "next/font/google";

import { SupabaseProvider } from "@/components/providers/supabase-provider";

import { SupabaseAuthProvider } from "@/components/providers/supabase-auth-provider";

import createClient from "../../utils/supabase-server";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const revalidate = 0;

const catamaran = Catamaran({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Movie Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let supabase = createClient();
  let {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={catamaran.className}>
        <SupabaseProvider>
          <SupabaseAuthProvider serverSession={session}>
            <Navbar />
            {children}
            <ToastContainer />
          </SupabaseAuthProvider>
          <Footer />
        </SupabaseProvider>
      </body>
    </html>
  );
}
